default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_wello_development

test:
  <<: *default
  database: backend_wello_test

production:
  adapter: sqlite3
  database: db/production.sqlite3
# production:
#   <<: *default
#   database: backend_wello_production
#   username: deploy
